# Generated by Django 4.2.13 on 2025-06-04 12:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Vorname des Mitglieds', max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(help_text='Nachname des Mitglieds', max_length=100, verbose_name='Nachname')),
                ('birth_date', models.DateField(help_text='Geburtsdatum im Format TT.MM.JJJJ', verbose_name='Geburtsdatum')),
                ('personnel_number', models.CharField(blank=True, help_text='Optional - FF Mitglieder haben keine Personalnummer', max_length=50, null=True, verbose_name='Personalnummer')),
                ('issued_date', models.DateField(default=django.utils.timezone.now, help_text='Datum der Ausweiserstellung', verbose_name='Ausgestellt am')),
                ('valid_until', models.DateField(help_text='Automatisch: Ausgestellt am + 5 Jahre', verbose_name='Gültig bis')),
                ('profile_picture', models.ImageField(blank=True, help_text='Wird automatisch zu vorname.nachname.jpg umbenannt', null=True, upload_to=members.models.member_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profilbild')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_active', models.BooleanField(default=True, help_text='Deaktivierte Mitglieder werden nicht für neue Ausweise verwendet', verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Mitglied',
                'verbose_name_plural': 'Mitglieder',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name', 'birth_date')},
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importiert am')),
                ('total_rows', models.IntegerField(verbose_name='Gesamte Zeilen')),
                ('successful_imports', models.IntegerField(verbose_name='Erfolgreich importiert')),
                ('failed_imports', models.IntegerField(verbose_name='Fehlgeschlagen')),
                ('error_log', models.TextField(blank=True, verbose_name='Fehlerprotokoll')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Importiert von')),
            ],
            options={
                'verbose_name': 'Import-Protokoll',
                'verbose_name_plural': 'Import-Protokolle',
                'ordering': ['-imported_at'],
            },
        ),
    ]
