# Generated by Django 4.2.13 on 2025-06-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_card_number_member_card_number_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='card_number_prefix',
        ),
        migrations.RemoveField(
            model_name='member',
            name='manual_validity',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_type',
        ),
        migrations.AlterField(
            model_name='member',
            name='personnel_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personalnummer'),
        ),
    ]
