# Generated by Django 4.2.13 on 2025-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='card_number',
            field=models.CharField(default='000000', help_text='Wird automatisch generiert', max_length=20, unique=True, verbose_name='Ausweisnummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='card_number_prefix',
            field=models.CharField(blank=True, choices=[('', 'Kein Präfix'), ('BF', 'BF'), ('FF', 'FF'), ('JF', 'JF')], help_text='Optional - wird automatisch basierend auf Mitarbeitertyp vorgeschlagen', max_length=10, verbose_name='Ausweisnummer-Präfix'),
        ),
        migrations.AddField(
            model_name='member',
            name='manual_validity',
            field=models.BooleanField(default=False, help_text='Für Externe und Praktikanten', verbose_name='Manuelle Gültigkeit'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('BF', 'Berufsfeuerwehr'), ('FF', 'Freiwillige Feuerwehr'), ('JF', 'Jugendfeuerwehr'), ('STADT', 'Stadt'), ('EXTERN', 'Extern'), ('PRAKTIKANT', 'Praktikant')], default='FF', max_length=20, verbose_name='Mitarbeitertyp'),
        ),
        migrations.AlterField(
            model_name='member',
            name='personnel_number',
            field=models.CharField(blank=True, help_text='Optional - FF Mitglieder haben meist keine Personalnummer', max_length=50, null=True, verbose_name='Personalnummer'),
        ),
    ]
