# Generated by Django 4.2.13 on 2025-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_card_number_member_card_number_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='card_number_prefix',
            field=models.CharField(blank=True, choices=[('', 'Kein Präfix'), ('FF', 'FF'), ('JF', 'JF')], help_text='Optional - wird automatisch basierend auf Mitarbeitertyp vorgeschlagen', max_length=10, verbose_name='Ausweisnummer-Präfix'),
        ),
        migrations.AlterField(
            model_name='member',
            name='issued_date',
            field=models.DateField(blank=True, help_text='Datum der Ausweis-Erstellung (leer = noch nicht erstellt)', null=True, verbose_name='Ausgestellt am'),
        ),
        migrations.AlterField(
            model_name='member',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig bis'),
        ),
    ]
